In [2]:
# after pip install tensorflow
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.1


In [3]:
# Fundamental concepts of TF using TF

# Introduction to Tensors

In [3]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check number of demensions of a tensor(ndim stands for number of demensions)
scalar.ndim

0

In [5]:
# Create a vectio
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Create a matrix(has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify the datatype


In [10]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# What is the number demensions of another_matrix?
another_matrix.ndim

2

In [12]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor.ndim

3

What we covered so far:

-Scalar: a single number -Vector: a number with direction (e.g. wind speed and direction)

Matrix: a 2-demensional array of numbers
Tensor: an n-dimentional array of numbers ( when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimentional tensor is a vector)

# Creating tensors with tf.Variable

In [14]:
# Createthe same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor # need ',' when calling more than 1

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [15]:
# change one element in changable tensor
changeable_tensor[0] = 7
changeable_tensor
# results in error

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
# lets try .assign() (after looking it up, that is)
changeable_tensor[0].assign(7)
changeable_tensor
# this worked

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
# lets try with unchangable
# unchangeable_tensor[0] = 7
# error

unchangeable_tensor[0].assign(7)
unchangeable_tensor
# error : object has no attribute to assign

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Above demonstrates the difference between constant and variable tensors. similar to const and let.

### Creating random tensors
tensors of some arbitrary size which contain random numbers

In [18]:
# Create two random (but the same) tensor
random_1 = tf.random.Generator.from_seed(42) # if the seed is the same they are the same randiom numbers
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7) # we change the seed and we get diffrent random numbers
random_2 = random_2.normal(shape=(3, 2))

# are they equal?
random_1, random_2, random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

neural networks tend to start with random data that is then slightly adjusted as new information is gathered

# Shuffel the order of elements in a tensor

the order our data is in can effect how the data learns

In [19]:
# shuffle tensor (avoiding inherent order bias
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# not_shuffled.ndim # shows us there are 2 attributes

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [20]:
# tun it a few times to see we get different shuffle order
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [23]:
# adding seed to our shuffle
tf.random.set_seed(42) 
tf.random.shuffle(not_shuffled, seed=42) # then call in function
# now the order dosent change
# both needed for the global seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

# Other ways to make tensors

In [24]:
tf.ones([10,7])
# much like numpy

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy arrays into tensors

difference between Numpy arrays and tf tensors, tensors run on gpu which is much faster.

In [26]:
# turning numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # not-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])