In [33]:
# after pip install tensorflow
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.1


In [34]:
# Fundamental concepts of TF using TF

# Introduction to Tensors

In [35]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [36]:
# check number of demensions of a tensor(ndim stands for number of demensions)
scalar.ndim

0

In [37]:
# Create a vectio
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [38]:
# Check the dimension of our vector
vector.ndim

1

In [39]:
# Create a matrix(has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [40]:
matrix.ndim

2

In [41]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify the datatype


In [42]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [43]:
# What is the number demensions of another_matrix?
another_matrix.ndim

2

In [44]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [45]:
tensor.ndim

3

What we covered so far:

-Scalar: a single number -Vector: a number with direction (e.g. wind speed and direction)

Matrix: a 2-demensional array of numbers
Tensor: an n-dimentional array of numbers ( when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimentional tensor is a vector)

# Creating tensors with tf.Variable

In [46]:
# Createthe same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor # need ',' when calling more than 1

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [47]:
# change one element in changable tensor
changeable_tensor[0] = 7
changeable_tensor
# results in error

TypeError: 'ResourceVariable' object does not support item assignment

In [48]:
# lets try .assign() (after looking it up, that is)
changeable_tensor[0].assign(7)
changeable_tensor
# this worked

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [50]:
# lets try with unchangable
# unchangeable_tensor[0] = 7
# error

unchangeable_tensor[0].assign(7)
unchangeable_tensor
# error : object has no attribute to assign

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Above demonstrates the difference between constant and variable tensors. similar to const and let.

### Creating random tensors
tensors of some arbitrary size which contain random numbers

In [51]:
# Create two random (but the same) tensor
random_1 = tf.random.Generator.from_seed(42) # if the seed is the same they are the same randiom numbers
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7) # we change the seed and we get diffrent random numbers
random_2 = random_2.normal(shape=(3, 2))

# are they equal?
random_1, random_2, random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

neural networks tend to start with random data that is then slightly adjusted as new information is gathered

# Shuffel the order of elements in a tensor

the order our data is in can effect how the data learns

In [52]:
# shuffle tensor (avoiding inherent order bias
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# not_shuffled.ndim # shows us there are 2 attributes

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [53]:
# tun it a few times to see we get different shuffle order
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [54]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [55]:
# adding seed to our shuffle
tf.random.set_seed(42) 
tf.random.shuffle(not_shuffled, seed=42) # then call in function
# now the order dosent change
# both needed for the global seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

# Other ways to make tensors

In [56]:
tf.ones([10,7])
# much like numpy

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [57]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy arrays into tensors

difference between Numpy arrays and tf tensors, tensors run on gpu which is much faster.

In [58]:
# turning numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # not-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [59]:
# lost me a bit 

# 20. Getting information from your tensors (tensor attributes)


Shape - the length(number of elements) of each of the demensions of a tensor.
tensor.shape

Rank - The number of tensor denmensions. A scalar has rank 0, a vector has rank 1,a matrix is rank2, a tensor has rank n.
tensor.ndim

Axis or demension - A particular demension of a tensor.
tensor[0]
tensor[:, 1]...6

Size - the total number of items in the tensor.
tf.size(tensor)

In [60]:
# create a ran 4 tensor(4 deminsions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [61]:
rank_4_tensor[0]
# the first set (0 indexed)

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [62]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [68]:
# get variout attributesa of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elaments along the 0 axis:", rank_4_tensor.shape[-1])
print("Elaments along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in out tensor:", tf.size(rank_4_tensor))
# we can do it with numpy (for convience)

print("Total number of elements in out tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elaments along the 0 axis: 5
Elaments along the last axis: 5
Total number of elements in out tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in out tensor: 120


# Indexing tensors

In [69]:
# tensors can be indexed  just like python lists

In [71]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [72]:
# the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [76]:
# first elenent from each dimension from each except for the final one
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [81]:
# rank_4_tensor[:1, :1,  :, :1]
# rank_4_tensor[:, :1,  :, :1]
rank_4_tensor[:, :1,  1:, :1]

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.]]]], dtype=float32)>

In [83]:
rank_2_tensor = tf.constant([[10,7],
[3,4]])

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [86]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [87]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [88]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [90]:
# get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [95]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [96]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [98]:
# expand the 0 axis
tf.expand_dims(rank_2_tensor, axis=0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

# 22. Manipulating tensors with basic operations

In [99]:
# bsadic operations: +,-,*,/


In [101]:
# add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[2,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 14]])>

In [107]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [22, 24]])>

In [109]:

# tensor = tensor + 10# unless we change it 
# # adds 10 to every number in tensor
# tensor
# tensor * 10# multiplication
# tensor - 30# sybtraction
# tf.multiply(tensor, 10)# we can use the tensorflow built-in function too

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 47],
       [42, 44]])>

# 23. Matrix multiplication with tensors part 1
one of the most common tensor operationm

resource for visualization : http://matrixmultiplication.xyz/

In [114]:
# matrix multiplication
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[50 47]
 [42 44]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4474, 4418],
       [3948, 3910]])>

In [115]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2500, 2209],
       [1764, 1936]])>

In [117]:
# matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4474, 4418],
       [3948, 3910]])>

In [119]:
tensor.shape

TensorShape([2, 2])

In [124]:
# create a tensor (3,2) tensor
x = tf.constant([[1,2],
[3,4],
[5,6]])
# create another (3,2) tensor
y = tf.constant([[7,8],
[9,10],
[11,12]])

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [125]:
x * y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]])>

In [129]:
# x @ y
# tf.matmul(x,y)
# matrix size incompatable 

# the inner dimensions must match
# the resulting matrix has the shape of the inner dimensions